services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_docker
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    user: root
    restart: unless-stopped
